artifacts_root: artifacts

data_ingestion:
  root_dor: artifacts/data_ingestion
  sourc_url: https:/github.com/entbappy/Branching-tutorial/raw/master/Chicken-fecal-images.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion